name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }} 
          known_hosts: 'dawd'
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: Adding Known Hosts
        run: ssh-keyscan -H 84.201.189.81 >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: |
          git status
          sudo touch cat.txt
          sudo rsync -avz ./cat.txt cuzkov@84.201.189.81:/
