name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
  
      - name: colllect-static
        run: |
          git clone https://github.com/frontend-park-mail-ru/2021_1_Noskool-team.git

      - name: Deploy to sandbox via rsync
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
          RSYNC_TARGET: /front
          RSYNC_SOURCE: /2021_1_Noskool-team
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_USERNAME: cuzkov
          SSH_HOSTNAME: 84.201.189.81
