# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.KNOW_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: build-static
        run: |
          ssh -i $SSH_KEY_PATH cuzkov@84.201.189.81
          cd frontend
          sudo apt install git
          git clone https://github.com/frontend-park-mail-ru/2021_1_Noskool-team.git
          cd ./2021_1_Noskool-team
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.KNOW_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
