name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }} 
          known_hosts: ${{secrets.KNOW_HOSTS}}
      - name: Deploy with rsync
        run: |
          git clone https://github.com/frontend-park-mail-ru/2021_1_Noskool-team.git    
          ls
          echo "123"
          sudo rsync -avz ./2021_1_Noskool-team cuzkov@84.201.189.81:/
