name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.KNOW_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: build-static
        run: |
          ssh cuzkov@84.201.189.81
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.KNOW_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - name: fd
        run: |
            echo "123"
            mkdir fro
            ls
            echo "123"
